### PR TITLE
X.Prompt: Document, simplify completion window implementation

### PR DESCRIPTION
**Pull request by slotThe**
### Description

`X.Prompt` is big.  And ugly.  I'd really like to revamp some of the internals (thankfully none of the `XPState` stuff is exported) but quite frankly I just don't understand some of the code in its current state.  This is a first effort to document some of the internal functions, so they may be more greatly simplified in the future.  I focused mostly on the X-specific part of the completion window implementation but this is still pretty long, sorry about that.

There are already a few simplifications in here that I couldn't resist making straight away:

* [X.Prompt: Make ComplWindowDim a proper type](https://github.com/xmonad/xmonad-contrib/commit/728e933848a317a5b2a31fadb37f65c8748d07a3)
  This gets rid of the horrible tuple implementation
  ``` haskell
    type ComplWindowDim = (Position,Position,Dimension,Dimension,Columns,Rows)
  ```
  and makes this a proper record type so we can a) give its fields meaningful names and b) make these fields strict.

* [X.Prompt: Simplify nextComplIndex](https://github.com/xmonad/xmonad-contrib/commit/34244f343f37a1cb58abdfa143f0368924f5b9dd)
  The logic for deciding in `nextComplIndex` was simplified and the extra argument was removed.

* [X.Prompt: Remove non-IORef complWin](https://github.com/xmonad/xmonad-contrib/commit/591d94204517d604426a90cc92be01d0efc7740b)
  We used to have two `complWin` fields, but they were always updated in tandem.  This means that we can just get rid of one of the fields. 

* [X.Prompt: Calculate prompt width once at the start](https://github.com/xmonad/xmonad-contrib/commit/ff856badf6f4849085c3eea1a27538b947d56855)
  The prompt doesn't change its size while it's open, so it suffices to calculate its width once at the start.

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  ~~- [ ] I updated the `CHANGES.md` file~~

  ~~- [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)~~

### CODE REVIEW

**Review by TheMC47 — APPROVED** [review]
LGTM, I admit I only skimmed through the commits because I'm unfamiliar with the code, but the looks like a net improvement. Thanks for working on this! Feel free to wait for another feedback, or go ahead with merging this, I don't think there's a problem

**Comment by slotThe** [comment]
> LGTM, I admit I only skimmed through the commits because I'm unfamiliar with the code, but the looks like a net improvement. Thanks for working on this! Feel free to wait for another feedback, or go ahead with merging this, I don't think there's a problem

Thanks for the review!  I think I'll wait for more feedback; this is not a crucial bugfix and there's no hurry to get this merged quickly (this is asuming that someone else _will_ look at it at some point in the future ;))

**Comment by slotThe** [comment]
(rebase)

**Comment by slotThe** [comment]
(Yet another rebase)

I'm going to merge this soon; the constant rebases are just creating unecessary noise and this has been my daily driver for a while now, so nothing huge can be amiss

**Pull request merged**
