### PR TITLE
Add layout hook for ScreenCorners.

### PR DESCRIPTION
**Pull request by kurnevsky**
It is needed because other windows can cover ours corner windows.

### CODE REVIEW

**Comment by kurnevsky** [comment]
Maybe it also can be done with StackMode = TopIf. I will check it.

**Comment by kurnevsky** [comment]
I checked - with StackMode we also need to specify sibling window, so i don't think that it is usable.

**Comment by kurnevsky** [comment]
Maybe, would be better to use logHook?

**Comment by byorgey** [comment]
Thanks!

**Pull request merged**
