### PR TITLE
Use minimize in scratchpads

### PR DESCRIPTION
**Pull request by f1u77y**
### Description

Use X.A.Minimize instead of NSP workspace for managing scratchpads. Rationale is described in #90.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [ ] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by pjones** [comment]
I like this idea a lot.  

When you get around to writing the entries in `CHANGES.md` be sure to describe the steps necessary to migrate any configuration that might stop compiling.

**Comment by f1u77y** [comment]
I have two questions about some non-trivial changes in this area:
1. Some modules do still have and export their functions for filtering out workspaces. I think that practically it's required only for "NSP" workspace but I of course can be wrong, so if someone has idea about what to do with these functions, leave feedback please. 
2. (Maybe it's a bit offtopic) Activating and then deactivating NamedScratchpad may lead to enexpected window activation(we may activate not the same window we came from, which is expected by user). That should be in the old version too.

**Comment by pjones** [comment]
I have a few named scratch pads and when I deactivate one, the window that was focused before activating the scratch pad will be focused again.  This is pretty important for me.  

For example, one of my scratch pads is my password manager.  When I close the password manager scratch pad I want to be able to paste a password into the previously focused window without having to change the current focus to the correct window.

**Comment by skewerr** [comment]
Could this mess with X.A.Minimize's per-workspace stacks? I'm a bit tired right now to test it with multiple workspaces and minimized windows(the way I've been using them for a while), but I'll leave this here and come back if/when I eventually do.

My question is: if I'm in workspace \#1, minimize a window A with a keybind to `withFocused minimizeWindow`, use a keybind to invoke a named scratchpad that spawns window B into the stack, then I send it away from the same workspace \#1, when I use a keybind to `withLastMinimized maximizeWindow`, will I see the scratchpad window B or window A? What about other workspaces, in case I send the scratchpad away from workspace \#1 and invoke `withLastMinimized maximizeWindow` from workspace \#2?

**Comment by b0o** [comment]
@f1u77y Thank you for this patch, I was having tons of issues using `marshallPP` from `X.L.IndependentScreens` and your patch fixed my issue - turned out `IndependentScreens` doesn't know how to handle the `NSP` workspace since it expects all workspaces to follow its naming convention.

**Comment by NickHu** [comment]
I would like to get this merged too, since the `NSP` workspace always seemed like a hack anyway

**Comment by eprst** [comment]
LGTM, but how does it play with the task bars? Say if I have 10 hidden scratchpads, will I see all 10 in the taskbar panel, e.g. if using xmonad with xfce?
We could probably add `_NET_WM_STATE_SKIP_TASKBAR` to `_NET_WM_STATE`, but it is supposed to be managed by the app, not WM.

**Comment by geekosaur** [comment]
Supposed to be, but that didn't stop me from writing http://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Util-NoTaskbar.html.

**Comment by byorgey** [comment]
Reviewing the discussion here, it looks like one potentially serious objection that hasn't been addressed (if I'm understanding correctly) is that currently, when you pull up a named scratchpad and then banish it again, focus returns to the most recently focused window.  But with this change the focus will go someplace random instead.  Is that correct?  I think I would be annoyed by the change.

**Comment by ivanbrennan** [comment]
> ...currently, when you pull up a named scratchpad and then banish it again, focus returns to the most recently focused window.
@byorgey I'm not experiencing that with the current implementation. I _want_ it to behave that way, but at the moment, banishing the scratchpad causes the lowest window in the stack to be focused, rather than the most recently focused window.

**Comment by byorgey** [comment]
@ivanbrennan strange.  I just tested this again with my setup to be sure, and I am indeed seeing the behavior I described --- after banishing a named scratchpad the focus returns to whichever window was focused previously.  The behavior you describe definitely seems wrong. Could you open a new ticket with a minimal config that shows that behavior?

**Comment by ivanbrennan** [comment]
@byorgey It seems to be the use of [scratchpads in combination with sublayouts](https://github.com/xmonad/xmonad-contrib/pull/376#issuecomment-687109644) that causes the behavior I'm seeing. Here's a minimal config I used to repro:
```haskell
import XMonad
import XMonad.Layout.SubLayouts (subLayout)
import qualified XMonad.Util.NamedScratchpad as NS
import qualified Data.Map as M

keys' = const . M.fromList $
  [ ((mod4Mask, xK_o), spawn (terminal def)),
    ((mod4Mask, xK_Shift_R), NS.namedScratchpadAction scratchpads "scratchpad")
  ]

scratchpads = [NS.NS name command (appName =? name) NS.defaultFloating]
  where
    name = "scratchpad"
    command = terminal def ++ " -name " ++ name

layoutHook' = subLayout [] tiled tiled
  where
    tiled = Tall 1 (3/100) (1/2)

main = xmonad def
  { keys = keys',
    manageHook = NS.namedScratchpadManageHook scratchpads,
    layoutHook = layoutHook'
  }
```

**Comment by slotThe** [comment]
I will close this, since it'll probably need to be rewritten when we tackle (parts of) #591 anyways

**Pull request closed without merging**
