### PR TITLE
X.A.WorkspaceNames: add get(Current)WorkspaceName

### PR DESCRIPTION
**Pull request by liskin**
(a cleaner version of #103, possibly)

### CODE REVIEW

**Comment by IvanMalison** [comment]
Yeah agreed. Thanks!

**Comment by byorgey** [comment]
Thanks!

**Comment by IvanMalison** [comment]
@liskin @byorgey After trying to use this in my own config, I've decided that this interface is actually harder to use in some ways because it requires access to the xmonad at all times to get the name of any particular workspace. I don't really see the advantage of hiding the underlying data structure in this case, since by exposing it we can do a bunch of stuff in pure functions that way.

What about exposing a function that exposes the underlying mapping?

**Comment by liskin** [comment]
Something like a `getWorkspaceNames :: X (WorkspaceId -> Maybe String)` ?

**Comment by liskin** [comment]
Oh, there already is a function `getWorkspaceNames` that's `X (WorkspaceId -> String)`. Maybe that should've been called `getWorkspaceIdsWithNames` or something as it's highly specialized for my xmobar usecase.

**Comment by IvanMalison** [comment]
getWorkspaceNames annoyingly adds the tag and a colon to the workspace name.

**Comment by liskin** [comment]
Okay, see https://github.com/xmonad/xmonad-contrib/pull/114

**Pull request merged**
