### PR TITLE
Fix WindowNavigation borders vs. transparency

### PR DESCRIPTION
**Pull request by geekosaur**
### Description

If pixels have an alpha channel, both `pixelToString` and
`averagePixels` fail and the result is `BadValue` errors and black
borders. Mask out the alpha channels so they work correctly.

Closes https://github.com/xmonad/xmonad/issues/395, https://github.com/xmonad/xmonad/issues/398

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: tested manually

  - [n/a] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by geekosaur** [comment]
Open question: should the masking be pushed down into the functions instead of being on their uses?

**Comment by slotThe** [comment]
> Open question: should the masking be pushed down into the functions instead of being on their uses?

I would say so; seems like the easiest way to prevent these kind of footguns

**Comment by liskin** [comment]
Seconded. Also, some explanatory comments about alpha not being welcome in Pixel for XQueryColor and the like might be good, and WindowNavigation isn't a good place for those.

**Comment by geekosaur** [comment]
Pushed the masking down inside `averagePixels` and `pixelToString`, with accompanying Haddock comments about the masking and why it's necessary.

**Review by liskin — APPROVED** [review]

**Pull request merged**
