### PR TITLE
DynamicBars: Add new multiPPFormat function

### PR DESCRIPTION
**Pull request by seanstrom**
Hey! So some weeks ago I asked about adding some new functionality to the `DynamicBars` module, discussed here #43, and I ended not refactoring to the ideal goal but felt I would share the progress that I had. Let me know if I can improve this and possibly a roadmap to the ideal addition. Thanks!

tag: @mathstuf @aavogt

### CODE REVIEW

**Comment by mathstuf** [comment]
Looks sensible to me.

**Comment by seanstrom** [comment]
@mathstuf Thanks! What are the next steps to getting this merged? A few more reviews, or are we good to go?

**Comment by mathstuf** [comment]
I don't have merge permissions here. I'd wait a bit and email the list; maybe someone who can merge will see it.

**Comment by byorgey** [comment]
Looks reasonable to me too.  Sorry for the long delay in anyone looking at it!

**Pull request merged**
