### PR TITLE
DocumentedKeys

### PR DESCRIPTION
**Pull request by janesser**
hello, 

the idea is to have a quick and searchable overview of all keybindings.
rather novice in haskell, open to comments.

cheers, Jan

### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [X] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: XXX

  - [ ] I updated the `CHANGES.md` file

### CODE REVIEW

**Review by slotThe — CHANGES_REQUESTED** [review]
I think this should rather be (and, indeed, is) handled by [X.U.NamedActions](https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Util-NamedActions.html), right?

**Comment by janesser** [comment]
> I think this should rather be (and, indeed, is) handled by [X.U.NamedActions](https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Util-NamedActions.html), right?

sure thing -
1 / shall move man-page stuff there, decoration etc. is much simpler there
2 / have a pointer, where exactly "Note that xmonad>=0.11 has by default a list of the default keybindings bound to M-S-/ or M-?." is implemented ?

**Comment by portnov** [comment]
I had an idea to extend X.A.NamedActions to support more structured headers and prefixes... like,
```
data Actions =
    Actions String (Maybe String) [Actions]
  | Action String String (X ())

actions = Actions "All keybindings" Nothing [
  , Actions "Window manipulations" (Just "M-w ") [
      Action "l" "Switch to window to the right" $ windowGo R False
    , Action "k" "Switch to window to the top" $ windowGo U False
    , ...
  , Actions "Subheader" (Just "key prefix") [ sub actions ]
]

addKeysFromActions :: Actions -> [(String, X ())]

actionsToMarkdown :: Actions -> String

actionsToHtml :: Actions -> String
...
```

or I suspect we can invent even more pretty EDSL, like

```
actions = header "All keybindings" [
    header "Window manipulations" [
      header "Switch to another window" `withPrefix` "M-w " [
        key "l" "Switch to window to the right" $ windowGo R False
      , key "k" "Switch to window to the top" $ windowGo U False
      , ...
      ]
      , header "Move windows around" `withPrefix` "M-w S-" [
          key "l" "Move window to the right" $ windowSwap R False
        , ...
      ]
    ]
]
```

(sorry for messed up indents, I hope you understood what I meant :))

**Comment by janesser** [comment]
@portnov the idea of _sectionizing_ the keybindings is great. i stumbled over some "submap" in `NamedActions` thing that could come in handy. ill include that in my thinking.

**Comment by janesser** [comment]
i substituted most of my config using X.U.NamedActions, see here: https://github.com/janesser/xmonad.hs/commit/3ddf243d550665c099aee876e6d869a47e5a5643

next TODOs
* find better display, instead of xmessage
** man-pages are searchable at least, still ghcup man structures are not to be relied on
** something out of X.U.Prompt could be useful
* further thoughts about hierarchy and ordering
** ideomatic: most frequently used on top. current default bindings on top is awesome for beginners and then interest shifts.
** me personally i'm fine with a 1-level hierarchy @portnov what was your motivation ?

**Comment by portnov** [comment]
For me personally, the interest is mostly theoretical, as I seem to be able to memorize shortcuts that I invented :) However, one could think of structure like

* Windows management
  * switching between windows
  * moving windows around
* workspaces management
  * switch to particular workspace
  * move current window to another workspace
  * bring a window from another workspace
* Screens management
  * shift focus to another monitor
  * move current workspace to another monitor
  * move current window to another monitor
* Layouts management
* Running specific programs 
* ...

**Comment by janesser** [comment]
Closing up.

**Pull request closed without merging**
