### PR TITLE
Remove keys type

### PR DESCRIPTION
**Pull request by exorcist365**
### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: that the documentation now displays properly

  ~~- [ ] I updated the `CHANGES.md` file~~

### CODE REVIEW

**Comment by TheMC47** [comment]
You're right about the haddock docs looking bad with this type hidden... Not the brightest idea I had.

However, I don't think this type should be exposed here. If we want to expose it, either do it in XMonad.Prelude and replace the occurrences, or, better yet, maybe from core.

**Comment by slotThe** [comment]
There might also be an argument for just removing this alias.  We're only using it in two places, really, so it might just unnecessarily confuse people

**Comment by exorcist365** [comment]
I mean... fair.

**Review by slotThe — APPROVED** [review]
LGTM.  @TheMC47 what do you think?

**Comment by TheMC47** [comment]
LGTM, just change the commit message to something more descriptive

**Comment by slotThe** [comment]
Thanks

**Pull request merged**
