### PR TITLE
Make strut cache global

### PR DESCRIPTION
**Pull request by f1u77y**

### CODE REVIEW

**Comment by liskin** [comment]
Thanks! Please have a look at https://github.com/liskin/xmonad-contrib/commits/managedocks-global-cache, I made some additional changes, improved your commit message and added another commit.

**Comment by f1u77y** [comment]
@liskin I agree with almost all of your improvements except using `refresh` instead of sending messages. The point is that sending messages to inactive layouts, it's just useless(sorry, my fault), that's why I think the most right way is to use only `sendMessage`.

**Comment by liskin** [comment]
Well, I did some research and found no modules in xmonad-contrib that use messages solely for the purpose of refreshing the layout without carrying a specific change to its configuration, while there are some that use `refresh`. That's why I used `refresh`, since it's clearly simpler (by lines of code, at least).

Regarding #76, I have no idea. Does `PerWorkspace`actively prevent messages being sent to the layout when it's active? Then it's a `PerWorkspace` bug. But it seems strange.

**Comment by f1u77y** [comment]
I think code is cleaner when something is run only when it needs to be run.

> Does `PerWorkspace` eactively prevent messages being sent to the layout when it's active?

It prevents messages being sent to the layout when it has never been active because it retranslates message to its first sub-layout when it hasn't been run initially while it should retranslate it to the second one.

**Comment by liskin** [comment]
> I think code is cleaner when something is run only when it needs to be run.

Okay, whatever. :-)

> It prevents messages being sent to the layout when it has never been active because it retranslates message to its first sub-layout when it hasn't been run initially while it should retranslate it to the second one.

Oh. Well, I never claimed that #76 was fixed by this, anyway. Point c) in https://github.com/liskin/xmonad-contrib/commit/fab2c2ad0e1720cd97d27a41c14b30ef9464b4d8 is a different issue, one that is now fixed indeed.

**Comment by lakshmivyas** [comment]
@f1u77y , @liskin - Thank you, both.  I just applied the patches (from @liskin's branch) and everything is awesome again :+1:

**Comment by davama** [comment]
Any chance this could be merged?
Thanks

**Comment by byorgey** [comment]
I don't really understand the issues or changes here, but if everyone involved is happy with it and you just need someone with a commit bit to click "merge" I would be happy to.  I'll merge in a few days unless I hear any objections before then.

**Comment by f1u77y** [comment]
@byorgey c48d81e37845184b62623aa08545e23859828f86 is just an enchancement that keeps docks state in `StateExtension` instead of per-layout state. It should not fix any issues(but it fixes one caused by X.L.Perworkspace bug(#76); will create a ticket with more information ASAP).

Another(e38fb3bdb8bba7e09cc598fd37a06545ce18229f) enchancement is described well enough in commit message, I think.

(oh, and how did I not notice that this StateExtension should be persistent; will fix)

**Comment by byorgey** [comment]
OK, thanks, makes sense.  I'll wait for the `StateExtension` fix then, ping me when you think it's ready to be merged.

**Comment by liskin** [comment]
Oh no, no no no.

c48d81e is everything but just an enhancement. That's the whole fix. And it too has a commit message that explains what is fixed and how.

And no, it should definitely not be persistent. If the strut cache somehow gets out of sync, an xmonad restart is all that needed to reset it. If you make it persistent, that won't be possible. Also, there's really no point in making a **cache** persistent, is it?

**Comment by liskin** [comment]
(So just to avoid any misunderstandings, I do think that it is currently ready to be merged and any additional changes may make it not ready. I did express this opinion by https://github.com/xmonad/xmonad-contrib/pull/80#pullrequestreview-120363)

**Comment by f1u77y** [comment]
@liskin 
Ok got it, and I've forgot about `docksStartupHook` that makes `PersistentExtension` completely useless. 

I also think that `modifyXS` should be moved to `X.U.ExtensibleState` because it's more common then just for internal usage in this module(I used exatly that function for fixing X.L.Minimize at least)

**Comment by f1u77y** [comment]
@byorgey it's ready to be merged

**Comment by geekosaur** [comment]
On Mon, Oct 24, 2016 at 6:29 PM, Bogdan Sinitsyn <notifications@github.com>
wrote:

> @byorgey <https://github.com/byorgey>
>
> c48d81e
> <https://github.com/xmonad/xmonad-contrib/commit/c48d81e37845184b62623aa08545e23859828f86>
>
> is just an enchancement that keeps docks state in StateExtension instead
> of per-layout state.


This actually trades one bug for another: currently you lose the strut
cache, and therefore existing struts, on mod-shift-space.
This would stop that, but also break the workaround that replaces the
binding with one that rebuilds the cache afterward: IIRC it would keep the
old struts because it can't be cleared from the outside, and then merge a
fixed one, leaving you with a semi-broken mixture.

-- 
brandon s allbery kf8nh                               sine nomine associates
allbery.b@gmail.com                                  ballbery@sinenomine.net
unix, openafs, kerberos, infrastructure, xmonad        http://sinenomine.net

**Comment by f1u77y** [comment]
@geekosaur as liskin mentioned, rebuilding of the cache now can be achieved by restarting xmonad

**Comment by f1u77y** [comment]
As liskin mentioned, rebuilding of the cache now can be achieved by 
restarting xmonad

**Pull request merged**
