### PR TITLE
UpdatePointer bugfix.

### PR DESCRIPTION
**Pull request by kurnevsky**
Sometimes cursor was stuck in one of the corners.

### CODE REVIEW

**Comment by byorgey** [comment]
This looks good to me.  My only comment is that perhaps `getWindowAttributesMaybe` should go in `Graphics.X11.Xlib.Extras` in the `X11` package instead of here?  It seems like it might be more generally useful.

**Comment by asjo** [comment]
I have tried to fix the getWindowAttributes failing problem in a different way: https://github.com/asjo/X11/commit/e5421307a02ea0cadcb381d282615d56a0e848c0 in https://github.com/xmonad/X11/pull/35 - (to solve the transparent border problem: https://github.com/xmonad/xmonad/pull/9) I don't know what method is preferred.

**Comment by kurnevsky** [comment]
@byorgey Perhaps you are right. I just thought that it assumed to use xGetWindowAttributes in such cases.
@asjo I think it would be good if getWindowAttributes will throw exception on zero status. It is better than return invalid result. But it might be useful to have another exception-less function like tryGetWindowAttributes.

**Comment by byorgey** [comment]
Yes, I agree it makes sense for `getWindowAttributes` to throw an exception rather than return an invalid result.  So let's also add `getWindowAttributesMaybe` (or `tryGetWindowAttributes`, I don't care too much what it's called) to the `X11` package.

**Comment by kurnevsky** [comment]
@byorgey ok, I rewrote this bugfix with Control.Exception.try because @dmwit didn't merge PR with tryGetWindowAttributes.

**Comment by kurnevsky** [comment]
Oops, sorry, it doesn't compile now.

**Comment by kurnevsky** [comment]
Fixed.

**Comment by kurnevsky** [comment]
(I didn't test it because xmonad-contrib doesn't compile with X11 head)

**Comment by bb010g** [comment]
Anything holding this back?

**Comment by geekosaur** [comment]
This looks okay to me. Has it actually been tested by now (noting the earliier "did not test because...")? The "brown paper bag" failure with struts was annoying enough to have let through.

**Comment by kurnevsky** [comment]
@bb010g @geekosaur This pullrequest will fix the bug only with version 1.7 of X11. The latest stable version doesn't throw an exception https://github.com/xmonad/X11/blob/1.6.1.2/Graphics/X11/Xlib/Extras.hsc#L976
But originally I fixed it with xGetWindowAttributes (in the first commit, this works with latest stable X11) and changed it to try $ getWindowAttributes after discussion above.

**Comment by pjones** [comment]
Please include an entry in `CHANGES.md` and after X11 1.7 is released we will merge this PR.  Thanks.

**Comment by kurnevsky** [comment]
Done.

**Comment by pjones** [comment]
Thanks!

**Comment by liskin** [comment]
So, um, will this fix work with X11 <1.7? Cause xmonad-contrib.cabal allows that.

**Comment by kurnevsky** [comment]
It won't. But it doesn't break building. However there was breking changes in X11 1.7 so I'm not sure if current xmonad works with older versions.

**Pull request merged**
