### PR TITLE
Add github actions for test

### PR DESCRIPTION
**Pull request by psibi**
### Description

Replaces Travis CI with github actions since travis doesn't work anymore: https://news.ycombinator.com/item?id=25338983

### Checklist

  - [ ] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

### CODE REVIEW

**Comment by psibi** [comment]
I will merge this in a couple of days unless there is any objection.

**Comment by TheMC47** [comment]
I just wanted to mention that currently "stack test" doesn't do anything, you'd need to take a lookt at #417 first. I tried to make the tests runnable through stack

**Comment by psibi** [comment]
@TheMC47 Your MR looks good. I think we should merge both of them.

Can you rebase your MR on top of this branch or should I rebase my branch on top of yours ?

**Comment by TheMC47** [comment]
I think you could go ahead and merge yours first, after that I'll rebase with master

**Pull request merged**
