### PR TITLE
Add HiddenEmptyWS to CycleWS

### PR DESCRIPTION
**Pull request by strokyl**
When I have multiscreen I think it's usefull to get the next empty workspace
that is not already displayed.

### CODE REVIEW

**Comment by strokyl** [comment]
I am pretty new to Haskell, I could not find associated test to this file. Tell me if there is any.

**Comment by f1u77y** [comment]
If you're talking about travis build, it failed to install xmonad from hackage.

**Comment by strokyl** [comment]
No I asked before the travis build failed. I saw it also fail for the master branch, so I guess the failure is not related to my PR.

**Comment by pjones** [comment]
I'm pretty sure Travis is configured to build xmonad from git.

On December 22, 2016 3:18:19 PM MST, Bogdan Sinitsyn <notifications@github.com> wrote:
>If you're talking about travis build, it failed to install xmonad from
>hackage.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/xmonad/xmonad-contrib/pull/130#issuecomment-268903172

-- 
Peter Jones, Founder, Devalot.com
Defending the honor of good code

**Comment by byorgey** [comment]
Yeah, I really don't understand what's going on with the travis build.  It failed only for GHC 8.0.1 with a strange error:
```
Preprocessing executable 'xmonad' for xmonad-0.12...
<command line>: cannot satisfy -package-id xmonad-0.12-DE9Mh3GjHOt3kdTRf1OcZi
  (use -v for more information)
```
In any case it seems clear it's unrelated to the changes in this PR.

**Comment by byorgey** [comment]
Thanks!

**Pull request merged**
