### PR TITLE
Clean up the code.

### PR DESCRIPTION
**Pull request by Ahanaf-Ether**
### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: XXX

  - [x] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by Ahanaf-Ether** [comment]
[Taken from](https://github.com/altercation/dotfiles-tilingwm/blob/master/.xmonad/lib/XMonad/Actions/ConditionalKeys.hs)

**Comment by Ahanaf-Ether** [comment]
Code is practically the same

**Review by slotThe — COMMENTED** [review]
I now remember bringing this up in https://github.com/xmonad/xmonad-contrib/pull/700#issuecomment-1090572232 when PerLayoutKeys was added.  The consensus seemed to be that the additional complexity is not worth having users search around for this.  Plus, the use-case seems to be quite narrow beyond the two modules that we have now

**Comment by Ahanaf-Ether** [comment]
i agree with you on this one.

**Comment by Ahanaf-Ether** [comment]
@geekosaur might as well merge it?

**Comment by slotThe** [comment]
> @geekosaur might as well merge it?

As you will see in the linked discussion, it was geekosaur who suggested that the additional of such a general module is probably unecessary.

**Comment by Ahanaf-Ether** [comment]
i will consider it as a no. But i will however make a new PR anyways. Making it shorter

**Comment by Ahanaf-Ether** [comment]
> i will consider it as a no. But i will however make a new PR anyways. Making it shorter

**Comment by geekosaur** [comment]
The big problem with generalizing the code isn't just that it's got few uses besides the two already there; it's that the user has to mess with ugly internals to do either of those things with the generalized one. It just doesn't seem to pull its weight while being user friendly (well, to the extent that Haskell ever is — but that also does weigh into it, it's complicated enough as it is).

**Pull request closed without merging**
