### PR TITLE
docs: Don't link to re-exports from XMonad.Config.Prime

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Review by geekosaur — APPROVED** [review]
👍🏽

**Comment by liskin** [comment]
I vaguely remember trying this a couple years ago but whatever version of Haddock we were using back then didn't seem to change its behaviour. Does this actually work now? That would be awesome! (But we might need to bump xmonad-docs to a newer version of ghc/haddock)

**Comment by sol** [comment]
> Does this actually work now? That would be awesome! (But we might need to bump xmonad-docs to a newer version of ghc/haddock)

I didn't actually try. I just did the edit quickly on GitHub from mobile device.

**Comment by slotThe** [comment]
From a cursory local test, seems like this doesn't work :(

**Comment by sol** [comment]
`{-# OPTIONS_HADDOCK hide #-}`

**Review by slotThe — APPROVED** [review]
> `{-# OPTIONS_HADDOCK hide #-}` does the trick.

Seems to work :+1:

> This has the disadvantage that we lose the documentation of `XMonad.Config.Prime`, but given that it is deprecated I hope this is an easy compromise.

Indeed, a small price to pay

**Comment by sol** [comment]
OK, great, from my side this is ready to merge.

**Comment by sol** [comment]
Is there anything else to discuss here? If not, can somebody click the merge button?

**Pull request merged**
