### PR TITLE
Delete _NET_WORKAREA instead of setting it

### PR DESCRIPTION
**Pull request by pjones**
### Description

References:

  * https://github.com/awesomeWM/awesome/commit/9c020877dd1357d7d42a29526d3567586f3db330

  * https://github.com/qtile/qtile/issues/847

  * https://github.com/i3/i3/commit/eec80838ab39377f18e3f68dc8a27923ae19e57e

  * https://github.com/xmonad/xmonad-contrib/pull/79

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [X] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [ ] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by xintron** [comment]
Getting the same error as the Travis CI builds using this patch:
```
XMonad/Hooks/ManageDocks.hs:271:9: error:
    • Variable not in scope:
        deleteProperty :: Display -> Window -> Atom -> IO ()
    • Perhaps you meant data constructor ‘TextProperty’ (imported from XMonad)
```

**Comment by pjones** [comment]
@xintron Sorry, I should have mentioned that you also need to use xmonad/X11#49 which adds `deleteProperty`.  The Travis builds are going to fail until I merge that PR and make a release :(

**Comment by xintron** [comment]
Ah, thanks for the info. Will retry it with that X11 patch applied as well. Currently running your branch https://github.com/pjones/xmonad-contrib/tree/pjones/workarea and that works as well from my tests throughout the day.

**Comment by pjones** [comment]
@xintron Thanks!  I appreciate you checking this stuff out.

**Comment by pjones** [comment]
Merged into the `release-0.13` branch.  Will show up on `master` after the release.

**Comment by IvanMalison** [comment]
@pjones What is the rationale behind not mergin to master until after the release?

**Comment by pjones** [comment]
It's on the release branch and will be part of the release.  

I'm not merging it directly to master (yet) because it requires X11 1.8 and I'd like to bring this PR plus the updated cabal file into master at the same time.

**Comment by IvanMalison** [comment]
ah okay that makes sense.

**Pull request closed without merging**
