### PR TITLE
Added functions to perform actions with the first minimized window.

### PR DESCRIPTION
**Pull request by skewerr**
### Description

I wanted to access the minimizedStack as if it were a queue, something which, despite the name, isn't a restriction to the module. The minimizedStack is just a `[Window]` anyways. This might not be particularly useful to many people, but it is to me.

I've compiled and am using the module with no errors, but have yet to write a minimal configuration for it to test with xmonad-testing. Given the size of the commit, I don't think this is *really* necessary, but let me know that I'm wrong.

### Checklist

  - [X] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [X] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by byorgey** [comment]
If this was just a matter of adding a few new functions, that wouldn't be too big of a deal, but it looks like you have changed the type of an exported function (`withMinimized`) as well, which could potentially break user configurations.  Can you explain why that is necessary?

**Comment by skewerr** [comment]
> Can you explain why that is necessary?

It isn't strictly necessary, but I did it that way so there wouldn't be
unnecessary repetition. Since `withMinimized` acts on the
`minimizedStack` as a whole, I made it so it'd also accept a modifier
function of type `X [Window] -> X [Window]` that'd be applied to
`XS.gets minimizedStack` in the line `minimized <- XS.gets
minimizedStack`.

After submitting the pull request I figured I could probably skip `fmap`
altogether by doing something like:

```Haskell
withMinimized :: ([Window] -> [Window]) -> ([Window] -> X a) -> X a
withMinimized modifier action = do
	minimized <- XS.gets minimizedStack
	currentStack <- withWindowSet $ return . W.index
	action . modifier $ minimized `L.intersect` currentStack
```

I'm still a Haskell noob, and now that I'm trying to learn the language,
I figured I could change the calls from `withLastMinimized'` and
`withFirstMinimized'` so that the later would compose `listToMaybe` with
`reverse` instead. This would avoid changing `withMinimized`'s type.
Would this be satisfactory?

```Haskell
withFirstMinimized' :: (Maybe Window -> X ()) -> X ()
withFirstMinimized' action = withMinimized (action . listToMaybe .  reverse)

withLastMinimized' :: (Maybe Window -> X ()) -> X ()
withLastMinimized' action = withMinimized (action . listToMaybe)

withMinimized :: ([Window] -> X a) -> X a
withMinimized action = do
	minimized <- XS.gets minimizedStack
	currentStack <- withWindowSet $ return . W.index
	action $ minimized `L.intersect` currentStack
```

Please tell me if anything's out of place or I've broken syntax.

**Comment by skewerr** [comment]
> Can you explain why that is necessary?

It isn't strictly necessary, but I did it that way so there wouldn't be unnecessary repetition. Since `withMinimized` acts on the `minimizedStack` as a whole, I made it so it'd also accept a modifier function of type `X [Window] -> X [Window]` that'd be applied to `XS.gets minimizedStack` in the line `minimized <- XS.gets minimizedStack`.

After submitting the pull request I figured I could probably skip `fmap` altogether by doing something like:

```Haskell
withMinimized :: ([Window] -> [Window]) -> ([Window] -> X a) -> X a
withMinimized modifier action = do
	minimized <- XS.gets minimizedStack
	currentStack <- withWindowSet $ return . W.index
	action . modifier $ minimized `L.intersect` currentStack
```

I'm still a Haskell noob, and now that I'm trying to learn the language, I figured I could change the calls from `withLastMinimized'` and `withFirstMinimized'` so that the later would compose `listToMaybe` with `reverse` instead. This would avoid changing `withMinimized`'s type. Would this be satisfactory?

```Haskell
withFirstMinimized' :: (Maybe Window -> X ()) -> X ()
withFirstMinimized' action = withMinimized (action . listToMaybe .  reverse)

withLastMinimized' :: (Maybe Window -> X ()) -> X ()
withLastMinimized' action = withMinimized (action . listToMaybe)

withMinimized :: ([Window] -> X a) -> X a
withMinimized action = do
	minimized <- XS.gets minimizedStack
	currentStack <- withWindowSet $ return . W.index
	action $ minimized `L.intersect` currentStack
```

Please tell me if anything's out of place or I've broken syntax.

**Comment by byorgey** [comment]
Sorry for the delay in responding.  Yes, in general doing things by just adding functions, and not modifying the type of any existing functions, is the way to go if possible, because it avoids breaking any existing uses of those functions that may be in any users' configs.

Currently, however, this PR seems to have type errors.  Check out the Travis build to see the error messages: https://travis-ci.org/xmonad/xmonad-contrib/builds/240383303?utm_source=github_status&utm_medium=notification .

**Comment by skewerr** [comment]
Sorry about that. Should be fixed now.

I was changing it quite a bit to add functions to swap the focused window with the first/last minimized window, so there were quite a few changes to force out of the commit. My bad. :/

**Comment by byorgey** [comment]
Thanks!

**Pull request merged**
