### PR TITLE
Add ModifySpacing message handling to SmartPacing and SmartSpacingWit…

### PR DESCRIPTION
**Pull request by strokyl**
…hEdge

### Description

I want to be able to dynamically change the spacing between window with smartSpacing so here is my pull request.

### CODE REVIEW

**Comment by pjones** [comment]
Please update `CHANGES.md` and then I'll do a review.  Thanks.

**Comment by strokyl** [comment]
@pjones Sorry, I have just updated the CHANGES.md

**Comment by strokyl** [comment]
🆙

**Comment by pjones** [comment]
@strokyl This PR is in the review queue.  Thanks!

**Comment by byorgey** [comment]
Looks good to me, thanks!

**Comment by IvanMalison** [comment]
Just for the record, this was already possible with multi-toggle.

As an example, see my config:
https://github.com/IvanMalison/dotfiles/blob/fabc451ceafc612ab13e1193367b1d5136b13c32/dotfiles/xmonad/xmonad.hs#L224

**Pull request merged**
