### PR TITLE
Export AvoidStruts constructor and doSink

### PR DESCRIPTION
**Pull request by sam-barr**
### Description

Export the constructor for the AvoidStruts layout modifier. I have a newtype wrapper on AvoidStruts in my config file to alter some of the behavior of AvoidStruts, and currently I have no option but to attempt to mirror the internals of AvoidStruts myself.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [x] I updated the `CHANGES.md` file

  - [x] I updated the `XMonad.Doc.Extending` file (if appropriate)

### CODE REVIEW

**Comment by sam-barr** [comment]
I also exported `doSink`, a function I contributed a few months ago but neglected to actually make visible.

**Comment by liskin** [comment]
@sam-barr Would you mind sharing (part of) your config so that we have a better idea about the motivation for this?

**Comment by sam-barr** [comment]
@liskin This is the layout modifier I have in my config

```
data AVState = Struts | NoStruts
    deriving (Read, Show)

toggleAV :: AVState -> AVState
toggleAV Struts = NoStruts
toggleAV NoStruts = Struts

data AV a = AV (AvoidStruts a) AVState
    deriving (Read, Show)

avoid :: LayoutClass l a => l a -> ModifiedLayout AV l a
avoid layout = let ModifiedLayout av l = avoidStruts layout in
                   ModifiedLayout (AV av Struts) l

instance LayoutModifier AV a where
    modifyLayout (AV av _) = modifyLayout av
    modifierDescription (AV _ st) = case st of
                                      Struts -> ""
                                      NoStruts -> "AVD"
    pureMess (AV av st) m = AV <$> (pureMess av m) <*> (pure newState)
        where
            newState = case fromMessage m of
                         Just ToggleStruts -> toggleAV st
                         _ -> st

    hook _ = asks config >>= logHook
```

Idealy, `AV` could just be a `newtype`, and wouldn't have to carry around this extra state parameter.
I should note that I can't just completely reimplement `AvoidStruts` in my config, also due to various things in the module not made public.

**Comment by sam-barr** [comment]
Ideally, I'd be able to have something like this instead:

```haskell
newtype AV a = AV { unAV :: AvoidStruts a }
    deriving (Read, Show)

instance LayoutModifier AV a where
    modifyLayout = modifyLayout . unAV
    modifierDescription (AA (AvoidStruts struts)) = if S.null struts then "" else "AVD"
    pureMess (AV av) m = AV <$> (pureMess av m)
    
```

**Comment by byorgey** [comment]
Looks good to me, thanks!

**Pull request merged**
