### PR TITLE
Redraw border when minimizing and restoring window

### PR DESCRIPTION
**Pull request by f1u77y**
Border color isn't set corretly with `modify`.

### CODE REVIEW

**Comment by geekosaur** [comment]
I'd imagine the original was intended to be used with `sendMessage`, which causes a refresh afterward; that *should* force the window border to be correct. since `windows` would then recolor all visible window borders. (And conversely, using `windows` here means a double update which could be slow with many windows.)

That said, this whole area is fairly complex. It is worth testing this fairly well, and possibly reviewing the sources of the messages to verify that they aren't doing things like sending without refresh (or if they are, finding out *why* they are because it may mean potential lurking issues).

**Comment by f1u77y** [comment]
> `windows` would then recolor all visible window border
As I can understand, `windows f` recolors only windows whose focus have been changed by `f`. So, modifying `windowset` by `modify` and not by `windows` leads to such a bug(#46).

>  (And conversely, using windows here means a double update which could be slow with many windows.)
I know that's bad, but restoring window *needs* to call `windows`. Anyway, restoring windows, I think, should not be called only by a message, because any modifying `windowset` from the internal layout functions AFAIK is bad. So, any solution that uses layout hooks for minimizing should run `windows` twice.

**Comment by geekosaur** [comment]
_"any modifying windowset from the internal layout functions AFAIK is bad"_

That's kinda the point; this *is* effectively an internal layout function, so I'm wary.

**Comment by f1u77y** [comment]
Ok, then now I see 2 ways to fix the bug:

1. Make `restoreNextMinimizedWindow` a function and call `windows` and other `X` stuff from it after `sendMessage`. That is more safe but still runs `windows` twice.
2. Rewrite `X.L.Minimize` without any layout hooks.

**Comment by f1u77y** [comment]
Closing that PR giving preference to #102

**Pull request closed without merging**
