### PR TITLE
Provide minimize layout that doesn't modify the layout name

### PR DESCRIPTION
**Pull request by IvanMalison**
### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [x] I updated the `CHANGES.md` file

### CODE REVIEW

**Comment by geekosaur** [comment]
FWIW, this is what X.L.Renamed is for; we can't do this for *every* small layout modifier, therefore shouldn't do it for some privileged few.

**Comment by IvanMalison** [comment]
> FWIW, this is what X.L.Renamed is for; we can't do this for _every_ small layout modifier, therefore shouldn't do it for some privileged few.

@geekosaur I already use renamed, and I still need this change, because I want to be able to name the individual layouts that I cycle through without having to rename everything.

Renamed is not great at picking out exactly how a few different layout modifiers applied/changed a name.

**Comment by geekosaur** [comment]
`quietMinimize = renamed [CutWordsLeft 1] . minimize`

You don't have to apply it only at the top level, or etc.

**Comment by IvanMalison** [comment]
> quietMinimize = renamed [CutWordsLeft 1] . minimize

Ah didn't know rename could do all of that.

**Pull request closed without merging**
