### PR TITLE
Fix rare issues with windows wrongly dissapearing after windowswallowing

### PR DESCRIPTION
**Pull request by elkowar**
### Description

In rare cases, there was an issue where the WindowSwallowing module failed to store the window stack correctly. Because of this it could happen that after closing a window that swallowed another, a unrelated window was unmapped. This PR fixes that issue by checking if the stored stack is in the expected state, and falling back to a simpler way of restoring the window if not. In these cases, the window is not guaranteed to be positioned exactly where the old child-window was, but that issue seems unavoidable if we failed to store the position of said child window previously. In most cases, this PR does not affect the behaviour.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [ ] I updated the `CHANGES.md` file (<- bugfix in module that was not yet part of a release, CHANES entry unnecessary)

  - [x] I updated the `XMonad.Doc.Extending` file (if appropriate)

### CODE REVIEW

**Comment by byorgey** [comment]
This seems fine, though it does immediately make me ask: why is the stack state sometimes stored incorrectly?  Can we fix that too?

**Comment by geekosaur** [comment]
One that comes immediately to mind is swallowing in the manageHook, since
the window won't be added to the StackSet in that case unless the hook
passes it on as well as swallowing it.

**Comment by elkowar** [comment]
the stack is stored "incorrectly" if the `configureEvent` is not fired when something there changes. idk _why_ that sometimes happens, but i have been able to reproduce cases where opening some windows just didn't fire that event (nor any other even we could realistically use for that). in that case, the difference between the stored stack and the actual stack is more than just that one window, which causes the issue

**Comment by geekosaur** [comment]
No configure event means an unmanaged window, which won't be in the
StackSet anyway.

**Pull request merged**
