### PR TITLE
ghc-9.0.1 compatibility fixes

### PR DESCRIPTION
**Pull request by l29ah**
### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)

  - [x] I updated the `CHANGES.md` file

  - [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)

### CODE REVIEW

**Comment by slotThe** [comment]
Thanks!

**Comment by liskin** [comment]
How did you manage to compile xmonad with ghc 9.0.1 with base being 4.16.0.0 and the setlocale package depending on base<4.15?

**Comment by liskin** [comment]
Well, I filed https://github.com/haskell-infra/hackage-trustees/issues/301

**Comment by l29ah** [comment]
Just loosened the `base` dependency (in fact, Gentoo maintainers did that for me).

**Comment by liskin** [comment]
Oh, the joys of not having to deal with cabal/stack. I envy you. :-)

**Pull request merged**
