### PR TITLE
Added XMonad.Hooks.FocusGuard

### PR DESCRIPTION
**Pull request by SirBoonami**
Disclaimer: I have positively no idea what I'm doing as my experience with X11 is absolutely zero. This module is the result of an afternoon of poking around in other source code and testing the outcome, and it seems to work well for me. From an expert's point of view it might be incredibly stupid.

### CODE REVIEW

**Comment by SirBoonami** [comment]
I'll have to retract this for now as I've run into some issues with it. Sometimes it's pretty hard to tell if a change is really active or not with the length and complexity of the toolchain involved.

**Comment by byorgey** [comment]
OK, let us know if you get it working!

**Comment by SirBoonami** [comment]
Okay, I finally got around to extensively testing it and the issues I encountered were unrelated.

I realize that in the meantime, a PR with a similar goal, but different approach (#110 by @liskin, marking the focus-grabbing window in question as urgent instead of selecively ignoring requests from certain applications) has been made, but I think my solution still provides a desirable alternative for more obnoxious cases.

Merging both hooks into a single module might be even better though, what do you think?

**Comment by liskin** [comment]
Actually your code does almost exactly the same thing as mine. How did I not notice this pull request here? :-(
(To my defense, I had the code for years, just last month decided it's time to clean it up and push upstream.)

Anyway, I intend to read all @geekosaur's suggestions on my pull requests and write some new code. Choosing between ignoring windows and marking them urgent will definitely be there. But I can't promise when I get to it.

**Comment by SirBoonami** [comment]
I closed it a while ago because I ran into some issues, which were, as it turned out, unrelated, so I just reopened it. I think the best solution for now is to wait for your PR to be accepted, then add my hook (maybe with some slight modifications) on top.

**Comment by SirBoonami** [comment]
Abandoned in favor of #128.

**Pull request closed without merging**
