### PR TITLE
X.P.RunOrRaise: Disambiguate directories and executables

### PR DESCRIPTION
**Pull request by slotThe**
##### X.P.RunOrRaise: Disambiguate directories and executables

When there is a directory and an executable of the same name `foo`, we
display `foo`, as well as `foo/` in the prompt, but selecting either one
of them will invariably run or raise the directory, as this test is done
beforehand.

Since directories already carry a trailing forward slash from the shell
prompt's `getShellCompl`, this is easily disambiguated by incorporating
an additional check.

It is duly noted that the same problem also exists for files and
executables.  This may be fixed in a similar way (adding a unique suffix
to files and checking for that), but since this would involve changing
`getShellCompl` and no-one has complained about this so far, it was
deemed "not worth it" for now.

Fixes: https://github.com/xmonad/xmonad-contrib/issues/616

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: I tested it manually, waiting for confirmation of @yusi1 as well.

  - [ ] I updated the `CHANGES.md` file
    TODO

  - [n/a] I updated the `XMonad.Doc.Extending` file (if appropriate)

### CODE REVIEW

**Comment by liskin** [comment]
> Isn't that files vs. directories vs. executables (of the same name)? I'm a bit confused, but do feel free to suggest ways to make this clearer

Not really, no. The problem is in mixing executable names in $PATH and relative file/dir names in the same list of completions.

In bash, there's no such confusion: https://www.gnu.org/software/bash/manual/html_node/Command-Search-and-Execution.html
When you type "xterm<kbd>↵</kbd>", it always looks for "xterm" in $PATH (after trying aliases, functions and builtins), even if there's an "xterm" executable in the current directory. When you type "x/xterm<kbd>↵</kbd>", there's a slash, so it doesn't search for it and executes it directly.

But in here, we don't have that slash distinction, so we need to disambiguate. But we're not disambiguating between "directories and files and executables", because "executables" are just files, we're disambiguating between "relative paths (files/dirs) and executables/commands in $PATH". It's probably just a wording nitpick, as all you need to do is change "executables" to "executables in $PATH" or "commands in $PATH" (or perhaps just "commands", although that's almost as unclear as "executables").

Anyway, as to whether this is worth dealing with, I'd think that preferring commands in $PATH to both files/dirs in the current directory would be the most natural thing as it's closer in behaviour to a shell. Adding a suffix like the attached patch would probably work, but it's a bit ugly. Can we perhaps refactor the check in RunOrRaise to try https://hackage.haskell.org/package/directory-1.3.6.2/docs/System-Directory.html#v:findExecutable first (you'll need to also check for a slash not being present as findExecutable doesn't do that)? That seems more like what the shell does and what I think might be the expected behaviour. Haven't really thought about what might break, though.

(That being said, absolutely do feel free to merge the fix you have so far, with improved commit message wording, and leave the rest for later.)

**Comment by slotThe** [comment]
> Not really, no. The problem is in mixing executable names in $PATH and relative file/dir names in the same list of completions.

Ah I see; thanks for the explanation.

> Anyway, as to whether this is worth dealing with, I'd think that preferring commands in $PATH to both files/dirs in the current directory would be the most natural thing as it's closer in behaviour to a shell. Adding a suffix like the attached patch would probably work, but it's a bit ugly. Can we perhaps refactor the check in RunOrRaise to try https://hackage.haskell.org/package/directory-1.3.6.2/docs/System-Directory.html#v:findExecutable first (you'll need to also check for a slash not being present as findExecutable doesn't do that)? That seems more like what the shell does and what I think might be the expected behaviour. Haven't really thought about what might break, though.

Since the old code definitely executes the file when it's an executable, I think this check can actually be done up-front without breaking anything; I did that in c83a46a92fe8e77567a97ba87016f71862ccd08f.

The problem with files in the current directory having the same name as something in `$PATH` is that right now they won't even show up in the prompt since we don't show the user paths, but only names of files/directories.  We would need to at least mark these "duplicates" somehow, which would involve messing with X.P.Shell internals and I'm really not up for that right now :)

**Comment by yusi1** [comment]
> > Not really, no. The problem is in mixing executable names in $PATH and relative file/dir names in the same list of completions.
> 
> Ah I see; thanks for the explanation.
> 
> > Anyway, as to whether this is worth dealing with, I'd think that preferring commands in $PATH to both files/dirs in the current directory would be the most natural thing as it's closer in behaviour to a shell. Adding a suffix like the attached patch would probably work, but it's a bit ugly. Can we perhaps refactor the check in RunOrRaise to try https://hackage.haskell.org/package/directory-1.3.6.2/docs/System-Directory.html#v:findExecutable first (you'll need to also check for a slash not being present as findExecutable doesn't do that)? That seems more like what the shell does and what I think might be the expected behaviour. Haven't really thought about what might break, though.
> 
> Since the old code definitely executes the file when it's an executable, I think this check can actually be done up-front without breaking anything; I did that in [c83a46a](https://github.com/xmonad/xmonad-contrib/commit/c83a46a92fe8e77567a97ba87016f71862ccd08f).
> 
> The problem with files in the current directory having the same name as something in `$PATH` is that right now they won't even show up in the prompt since we don't show the user paths, but only names of files/directories. We would need to at least mark these "duplicates" somehow, which would involve messing with X.P.Shell internals and I'm really not up for that right now :)
> 
> EDIT: As for breaking current functionality I'm hoping that @yusi1 will confirm that at least their use-case still works

@slotThe, just tested your fix in a VM and it does exactly what I wanted and fits my usecase, thanks for working on this everyone involved! :smile:

**Comment by liskin** [comment]
> Since the old code definitely executes the file when it's an executable, I think this check can actually be done up-front without breaking anything; I did that in [c83a46a](https://github.com/xmonad/xmonad-contrib/commit/c83a46a92fe8e77567a97ba87016f71862ccd08f).

The old code does, but the new code doesn't always. If you try to run e.g. `bin/something`, the old code would decide it's not a normal file and execute it (but not raise it! `pidof bin/something` won't find the pid). The new code doesn't do the executable check, so it'll invoke `xdg-open bin/something` instead. I have absolutely no idea if this breaks any meaningful workflows, though: stuff in `~/bin` will likely be on the $PATH, and also raising won't work, so…

**Comment by slotThe** [comment]
I'm willing to take that risk :)

**Comment by liskin** [comment]
There was a comment here from @yusi1 saying that this breaks inputs like /usr/bin/firefox, which it definitely does, and since it's a full path, `pidof` accepts that and raising would work before as well. That comment is now lost, or at least I don't see it now. Reintroducing the `getPermissions` check would fix this.

Anyway, I'm happy to merge this as it is, but I do need to say that the commit message is still the same as it was before we fixed the files vs. commands ambiguity, so it now claims that a problem still exists which it no longer does. :-)

**Comment by slotThe** [comment]
> I do need to say that the commit message is still the same as it was before we fixed the files vs. commands ambiguity, so it now claims that a problem still exists which it no longer does. :-)

The problem still exists insofar as what I said above about displaying files in path and files in the current directory:

> The problem with files in the current directory having the same name as something in $PATH is that right now they won't even show up in the prompt since we don't show the user paths, but only names of files/directories. We would need to at least mark these "duplicates" somehow

**Comment by slotThe** [comment]
> > I do need to say that the commit message is still the same as it was before we fixed the files vs. commands ambiguity, so it now claims that a problem still exists which it no longer does. :-)
> 
> The problem still exists insofar as what I said above about displaying files in path and files in the current directory:
> 
> > The problem with files in the current directory having the same name as something in $PATH is that right now they won't even show up in the prompt since we don't show the user paths, but only names of files/directories. We would need to at least mark these "duplicates" somehow

so I figured the commit message still applied

**Pull request merged**
