### PR TITLE
Add a flake.nix file

### PR DESCRIPTION
**Pull request by IvanMalison**
### Description

Include a description for your changes, including the motivation
behind them.

### Checklist

  - [x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)

  - [x] I've considered how to best test these changes (property, unit,
        manually, ...) and concluded: XXX

  - [x] I updated the `CHANGES.md` file

  - [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)

### CODE REVIEW

**Comment by IvanMalison** [comment]
This does need https://github.com/xmonad/xmonad/pull/316 in order to technically work properly, but I tested by pointing it at my branch.

**Comment by IvanMalison** [comment]
The build will fail until xmonad/xmonad#316 is merged

**Comment by liskin** [comment]
Hm, even though you [guarantee that the build would be 10× faster](https://github.com/xmonad/xmonad/pull/316#issuecomment-890308172) (😃), it's not really the case and the Nix workflow in xmonad-contrib is the slowest of the three. That's probably because xmonad-contrib is huge and benefits a lot from building modules in parallel by passing `-j` to GHC, and we do that in the two other workflows:
https://github.com/xmonad/xmonad-contrib/blob/master/cabal.haskell-ci#L15
https://github.com/xmonad/xmonad-contrib/blob/master/stack-master.yaml#L26
Can we do that in the Nix build as well? How?

**Comment by IvanMalison** [comment]
> it's not really the case and the Nix workflow in xmonad-contrib is the slowest of the three.

To be fair, that's because you cache dependencies as one giant blob for the other 2 systems and load them wholesale. Not really a fair comparison at all.

If you compared someone just running `stack build` or `cabal new-build` vs `nix build` on a freshly cloned repository it would indeed be 10x faster.

Another reason for it being slower is that the nix build does multiple versions of the build.

As for parallel building, it seems that this was enabled and then disabled:

https://github.com/NixOS/nixpkgs/pull/4554

If we really really want it, it should be possible to revert the revert and use a custom version of nixpkgs.

**Comment by IvanMalison** [comment]
Actually if you look at the build log, it looks like we are already using the -j flag:
```
xmonad> setupCompileFlags: -package-db=/build/setup-package.conf.d -j2 +RTS -A64M -RTS -threaded -rtsopts
```

**Comment by IvanMalison** [comment]
> To be fair, that's because you cache dependencies as one giant blob for the other 2 systems and load them wholesale. Not really a fair comparison at all.

Likely that caching /nix/store would help a lot, especially if we also add a flake.lock.

**Comment by liskin** [comment]
> Another reason for it being slower is that the nix build does multiple versions of the build.

Oh, yeah, looking at the logs it seems the nix build enables profiling so it compiles xmonad-contrib twice:

```
Sun, 01 Aug 2021 21:27:27 GMT
xmonad-contrib> [  1 of 295] Compiling XMonad.Actions.AfterDrag ( XMonad/Actions/AfterDrag.hs, dist/build/XMonad/Actions/AfterDrag.o, dist/build/XMonad/Actions/AfterDrag.dyn_o )
Sun, 01 Aug 2021 21:28:53 GMT
xmonad-contrib> [295 of 295] Compiling XMonad.Actions.EasyMotion ( XMonad/Actions/EasyMotion.hs, dist/build/XMonad/Actions/EasyMotion.o, dist/build/XMonad/Actions/EasyMotion.dyn_o )
```

```
Sun, 01 Aug 2021 21:28:55 GMT
xmonad-contrib> [  1 of 295] Compiling XMonad.Actions.AfterDrag ( XMonad/Actions/AfterDrag.hs, dist/build/XMonad/Actions/AfterDrag.p_o )
Sun, 01 Aug 2021 21:30:36 GMT
xmonad-contrib> [295 of 295] Compiling XMonad.Actions.EasyMotion ( XMonad/Actions/EasyMotion.hs, dist/build/XMonad/Actions/EasyMotion.p_o )
```

> it looks like we are already using the -j flag

Oh, okay. Still, the stack build is faster:

```
Sun, 01 Aug 2021 21:26:40 GMT
[  1 of 295] Compiling XMonad.Actions.AfterDrag
Sun, 01 Aug 2021 21:27:07 GMT
[295 of 295] Compiling XMonad.Actions.EasyMotion
```

~30 seconds instead of ~1 min 30 sec for the builds nix does. Any way to check if using `-j` instead of `-j2` helps?

Note that we only enable `-j` for xmonad-contrib, not for all the other packages, because those are built in parallel by stack/cabal. This was discussed here: https://github.com/xmonad/xmonad-contrib/pull/431, and I guess it might be one of the reasons it's not a good idea to enable it globally in nix either. So if we could just change the flake to add `-j` to ghc-options for xmonad-contrib, like we do for cabal and stack, that could be best?

I'm not sure caching the entire nix store is the correct solution here. I guess that might cut the first minute (the one where nix logs nothing and just does I don't what) off nix build, and then probably also the xmonad core build would be cached, but xmonad-contrib would still often be built from scratch, and that takes at least 3 minutes now. Oh and caching the flake.lock… we probably don't want that do we? That's not a good tradeoff. :-)

**Comment by IvanMalison** [comment]
@liskin One option would be to use nix develop and then run `cabal new-build` inside of that instead of using nix-build. Then we could customize the build flags in exactly the same way as we do with the other cabal builds.

**Comment by IvanMalison** [comment]
> Oh and caching the flake.lock… we probably don't want that do we? That's not a good tradeoff. :-)

All that flake.lock would do in this case is freeze the nixpkgs and xmonad depedencies at a specific version. If we ever needed to bump those we would do so explicitly.

**Comment by IvanMalison** [comment]
> ~30 seconds instead of ~1 min 30 sec for the builds nix does. Any way to check if using `-j` instead of `-j2` helps?

Looks like this flag gets set here:
https://github.com/NixOS/nixpkgs/blob/aaf9676fbb7fb4570216ca1e189a3dc769d62c45/pkgs/development/haskell-modules/generic-builder.nix#L185

seems like its being set to the number of cores which seems sensible to me.

**Comment by IvanMalison** [comment]
We could also disable profiling with: https://github.com/NixOS/nixpkgs/blob/aaf9676fbb7fb4570216ca1e189a3dc769d62c45/pkgs/development/haskell-modules/generic-builder.nix#L31

**Comment by liskin** [comment]
> seems like its being set to the number of cores which seems sensible to me.

I'll try stack build with `-j2` to see if it slows down to 1 min 30 sec or if that's something else.

> We could also disable profiling

Would it still use cached dependencies?

**Comment by liskin** [comment]
> I'll try stack build with `-j2` to see if it slows down to 1 min 30 sec or if that's something else.

Hm, it still builds it in 30 seconds. :-/

**Comment by IvanMalison** [comment]
> Would it still use cached dependencies?

Yes, we would only disable it for the xmonad-contrib package.

**Comment by liskin** [comment]
I'll go to bed now, so let's wrap it up somehow: ideally we'd figure out why ghc in nix build is three times slower than in stack/cabal builds, and fix that. This should turn 3 minutes into 1, and pull request checks won't get slower by merging this. If we fail to do that, caching nix store and possibly also disabling profiling should also cut it down to acceptable levels.

(I hope you don't mind me obsessing about these details. But I did get praise from contributors for speeding up the PR checks, so I'd love to keep them fast.)

**Comment by IvanMalison** [comment]
> I hope you don't mind me obsessing about these details

No, makes sense. quick ci is a good goal.

**Comment by IvanMalison** [comment]
@liskin The nix develop approach did seem to reduce the time it took somewhat (mostly bc the profile build no longer happens)

The Nix build is still about a minute and a half longer than the other builds. I think we would have to cache the nix store to fix this.

**Comment by IvanMalison** [comment]
Not that this is the best comparison, but on my local machine I get:
``
nix develop -c cabal v2-build -j4  55.33s user 1.69s system 99% cpu 57.065 total
```

**Comment by liskin** [comment]
> ideally we'd figure out why ghc in nix build is three times slower than in stack/cabal builds, and fix that

Turns out the haskell-ci (cabal-install) workflow was also a 1min30s, because only the stack build had `--fast` (`-O0`) — [fixed here](https://github.com/xmonad/xmonad-contrib/commit/8de415743d2765fe121c492109fa107c30e0d371). So that answers that bit. Can we tell Nix to disable GHC optimizations in the CI workflow without disabling it for all users of the flake?

> The nix develop approach did seem to reduce the time it took somewhat

Seems a bit ugly to invoke `cabal v2-build` manually. 😞 Are we really testing the flake then? 🤔

**Comment by IvanMalison** [comment]
> Seems a bit ugly to invoke `cabal v2-build` manually.  Are we really testing the flake then?

I would argue we're still getting most of what we need, since we are using nixDevelop. We are still using nix to process the cabal file, fetch all depdencies and build the environment in which the package is built.

The thing is that the alternative is to change what happens with defaultPackage, but I don't think we actually want those flags on by default right?

**Comment by liskin** [comment]
> but I don't think we actually want those flags on by default right?

Yeah, definitely not by default, only to make CI faster. :-/

**Comment by liskin** [comment]
Anyway, if you believe `nix develop … cabal v2-build` is good enough, I'm not going to challenge that as I really have no idea about the details there (same as the `nix flake check` thing, it looks desirable but I had no idea what it actually does ☺). So let's just add `-O0` to `cabal v2-build` and we should be good to go.

**Pull request merged**
